language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt
before_script:
  - mkdir -p tests/_coverage
script:
  - py.test tests/ --cov watson --cov-report term-missing
after_success:
  - coveralls --verbose
notifications:
  slack:
    secure: FGssGOei0T1FhVjDslrnJ1YUAAZxImTc/V0IDCWFt1Yti0034KG3bhMMk9Vpn5pBphluK4xaaSBzz1JxkotZmpvkF9n75OMxBy4Qj0zmD6fMDYsb9irisr4tQ4nOrQ4rtAZMUh0IsORFweX4GrgtHf5hDxsNwKYJ52igY0zMo1Y=
